---
all:
  children:
    web:
      hosts:
        web1:
          ansible_host: "{{ lookup('env', 'PORTFOLIO_PUBLIC_IP') }}"
          ansible_user: 'ubuntu'
          ansible_ssh_private_key_file: '/Users/yaboi/.ssh/root_portfolio'